version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:10.24
    resource_class: large # Actually necessary. Doesn't build on `small`. Haven't tested the classes in-between.
    steps:
      - checkout
      # Cache, see: https://circleci.com/docs/2.0/language-javascript/#sample-configuration
      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          command: |
            npm i
            npm run setheapsize
            npx grunt prod
            npx grunt exec:sitemap
      - save_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - persist_to_workspace:
          root: ~/
          paths:
            - project/
            - .cache
  deploy:
    docker:
      - image: cimg/node:14.19 # Dattel isn't compatible with Node < 12 but CyberChef requires 10. :(
    resource_class: medium
    steps:
      - attach_workspace:
            at: ~/
      - run:
          command: |
            sudo npm i -g dattel-client
            dattel deploy

workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
              - build
